# Create env:
# $ conda env create --force

name: word2vec
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python = 3.5
  - ipython > 5.0
  - jupyter >= 1.0
  - numpy
  - matplotlib
  - scikit-learn
  - tensorflow
  - setuptools
  - psutil
  - pip
  - rise
  - pip:
    - nbbrowserpdf
# Start env:
# $ source activate word2vec